on: push
jobs:
  job:
    strategy:
      matrix:
        os:
          - windows
          - macos
          - ubuntu
        package:
          - node
          - html
          - tsconfig
          - caddy
          - documentation
          - package
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        working-directory: ./${{ matrix.package }}/
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org/
      - run: npm install-ci-test
      - if: ${{ matrix.os == 'ubuntu' && startsWith(github.ref, format('refs/tags/{0}--', matrix.package)) }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
